### ISSUE TITLE
前端无法打开已上传的excel和word

### ISSUE THREAD

**Issue by whataxxday** [kuaifan/dootask#103]
### nginx容器日志：
192.168.1.210 - - [14/Jun/2022:17:31:29 +0800] "GET /office/7.0.0-132/doc/xlsx-193-1655198580/c/info?t=1655199089899 HTTP/1.1" 502 552 "http://192.168.1.240:2222/office/7.0.0-132/web-apps/apps/spreadsheeteditor/main/index.html?_dc=7.0.0-132&lang=zh&customer=ONLYOFFICE&frameEditorId=office_5036&parentOrigin=http://192.168.1.240:2222&uitheme=theme-classic-light" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36" "-"

### onlyoffice容器日志：
/var/log/onlyoffice/documentserver/nginx.error.log
2022/06/14 09:22:58 [error] 6275#6275: *349 connect() failed (111: Connection refused) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: , request: "GET /7.0.0-132/doc/docx-132-1655192470/c/info?t=1655198578660 HTTP/1.1", upstream: "http://[::1]:8000/doc/docx-132-1655192470/c/info", host: "192.168.1.240:2222", referrer: "http://192.168.1.240:2222/office/7.0.0-132/web-apps/apps/documenteditor/main/index.html?_dc=7.0.0-132&lang=zh&customer=ONLYOFFICE&frameEditorId=office_5036&parentOrigin=http://192.168.1.240:2222&uitheme=theme-classic-light"

**Comment by whataxxday** [comment]
### onlyoffice容器日志报错信息补充：

ds:docservice: ERROR (not running)
ds:docservice: ERROR (spawn error)
ds:converter: ERROR (not running)
ds:converter: ERROR (spawn error)
 * Reloading nginx configuration nginx
   ...done.
==> /var/log/onlyoffice/documentserver/converter/err.log <==
    at JSON.parse (<anonymous>)
    at loadConfigurationFile (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:49:17)
    at Object.configure (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:58:20)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/logger.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
==> /var/log/onlyoffice/documentserver/converter/out.log <==
==> /var/log/onlyoffice/documentserver/docservice/err.log <==
    at JSON.parse (<anonymous>)
    at loadConfigurationFile (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:49:17)
    at Object.configure (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:58:20)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/logger.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)

**Comment by whataxxday** [comment]
自测解决办法，在项目已启动的状态下，执行以下命令：
./cmd service supervisor start
